revert Commit 105ec67
Commit 105ec67 threw:

error: home.asm(55) -> home/trainers.asm(140): Unknown symbol "CheckFightingMapTrainers.trainerNotEngaging"

on make